"""PC-Bediener + FL Studio OpenCode-Addon.

Dieses Addon stellt bei jeder OpenCode-Sitzion die pcbediener MCP-Tools
und das gesamte FL-Studio-Bedienungswissen bereit.

Verwendung:
    import addon.pcbediener_addon as addon
    info = addon.init_addon()
    # oder direkt die Tools nutzen:
    addon.safety_status()
    addon.flstudio_info()
"""

from .pcbediener_addon import (
    init_addon,
    safety_status,
    safety_mode,
    exec_python,
    exec_powershell,
    exec_command,
    mouse_move,
    mouse_click,
    mouse_drag,
    mouse_scroll,
    keyboard_type,
    keyboard_press,
    keyboard_hotkey,
    clipboard_set,
    clipboard_get,
    sleep,
    window_list,
    window_focus,
    window_action,
    window_modal_state,
    window_health,
    window_activate,
    window_list_controls,
    window_set_text,
    window_invoke,
    window_menu,
    window_key_shortcut,
    process_list,
    process_info,
    process_start,
    process_kill,
    screenshot,
    screen_find_image,
    screen_wait_for_image,
    system_status,
    file_read,
    file_read_binary,
    file_write,
    file_list,
    file_tree,
    file_search,
    folder_create,
    file_move,
    file_copy,
    file_delete,
    app_rules_list,
    app_rule_get,
    app_rule_set,
    app_rule_break,
    flstudio_info,
    TOOLS,
    INSTRUCTIONS,
)

__version__ = "1.0.0"
__all__ = [
    "init_addon",
    "safety_status",
    "safety_mode",
    "exec_python",
    "exec_powershell",
    "exec_command",
    "mouse_move",
    "mouse_click",
    "mouse_drag",
    "mouse_scroll",
    "keyboard_type",
    "keyboard_press",
    "keyboard_hotkey",
    "clipboard_set",
    "clipboard_get",
    "sleep",
    "window_list",
    "window_focus",
    "window_action",
    "window_modal_state",
    "window_health",
    "window_activate",
    "window_list_controls",
    "window_set_text",
    "window_invoke",
    "window_menu",
    "window_key_shortcut",
    "process_list",
    "process_info",
    "process_start",
    "process_kill",
    "screenshot",
    "screen_find_image",
    "screen_wait_for_image",
    "system_status",
    "file_read",
    "file_read_binary",
    "file_write",
    "file_list",
    "file_tree",
    "file_search",
    "folder_create",
    "file_move",
    "file_copy",
    "file_delete",
    "app_rules_list",
    "app_rule_get",
    "app_rule_set",
    "app_rule_break",
    "flstudio_info",
    "TOOLS",
    "INSTRUCTIONS",
]
